### ISSUE TITLE
Calculate Bandwidth using 80th percentile of last 10 segments downloaded

### ISSUE THREAD

**Issue by flavioribeiro** [streamroot/clappr-p2phls-plugin#101]
http://www.ccs.neu.edu/home/cbw/4700/papers/p225.pdf

**Comment by flavioribeiro** [comment]
![image](https://cloud.githubusercontent.com/assets/244265/5158827/9e1164ba-7332-11e4-9641-c12d57d5a482.png)
![image](https://cloud.githubusercontent.com/assets/244265/5158828/aa023e16-7332-11e4-95ac-1aff90c83b4a.png)

**Comment by roberto** [comment]
:+1:

**Comment by flavioribeiro** [comment]
:v:
