### ISSUE TITLE
Remove underscore and jquery from dependencies

### ISSUE THREAD

**Issue by flavioribeiro** [streamroot/clappr-p2phls-plugin#16]

**Comment by flavioribeiro** [comment]
@thiagopnts we need to upload a new version of clappr on npmjs to fix this?

**Comment by thiagopnts** [comment]
probably, the current version has one option to build without jquery, but this build is not present on `dist/`, I will make this changes and publish a new version

**Comment by flavioribeiro** [comment]
@thiagopnts awesome! thank you for this.

**Comment by flavioribeiro** [comment]
Fixed under 0d713958cc2f01227fbe8c46e908fd43c79d3e35
