### ISSUE TITLE
support secure urls

### ISSUE THREAD

**Issue by ankurss** [streamroot/clappr-p2phls-plugin#35]
swarm can use filename-level to find correct chunks

level1: http://domain.com/hls/some-secure-code-12345-/filename-240p/chunk1.ts
level2: http://domain.com/hls/some-secure-code-67890-/filename-360p/chunk1.ts

**Comment by flavioribeiro** [comment]
hi @ankurss I think this commit solves your problem. If something goes wrong, please let me know.

**Comment by flavioribeiro** [comment]
hey @ankurss, I've noticed that streams generated by Wowza doesn't have this URL scheme. It just put the master and level playlists on the same directory and also the segments.

I'm afraid I'll need to revert this commit. Do you have a better solution? Maybe a flag on embed parameters to tell the plugin to "normalize" segment url's?
