### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by flavioribeiro** [streamroot/clappr-p2phls-plugin#54]
Add a step-by-step guide to teach people on how to deploy a clappr player using BemTV p2p plugin on their HLS transmissions.

**Comment by macbroadcast** [comment]
Thanks would appreciate ;)

**Comment by flavioribeiro** [comment]
Hi @macbroadcast, I've just finished a small tutorial, you can check it out at https://github.com/bemtv/bemtv#how-to-use-it-on-my-own-hls-transmission
