### ISSUE TITLE
Contribute  Server and Bandwith for Stress testing

### ISSUE THREAD

**Issue by macbroadcast** [streamroot/clappr-p2phls-plugin#61]
aloha,

I´ve set up a deployment server for bem.tv andclappr on ubuntu 12.04 LTS, 

http://87.230.18.206:3000/

The server has unlimited bandwith and i  would like to make some scalability testing in the next weeks with 100 -500 viewers.
Statistic plugin installed, but  not working yet. Hopefully i will win some more interested people from my area to improve things.
Meanwhile i am reading more documents and preparing a webpage in german.
I have some time at my hands to help test and think about new features.

greetings

**Comment by flavioribeiro** [comment]
Hi @macbroadcast, thank you for your interest. I saw on your html that P2PHLSStats is missing on your embed:

``` javascript

window.onload = function() {
  player = new WP3.Player({sources: ['http://cdn.bem.tv/stream/soccer2sec/playlist.m3u8'],
                            plugins: {playback: [P2PHLS]},
                            width: 640, height: 360,
                            poster: "http://www.bem.tv/assets/poster.png",
                            watermark: "http://bem.tv/assets/watermark3.png"
                          });
  player.attachTo(document.getElementById('player-wrapper'));
}
```

You need to change plugins line to: `plugins: {playback: [P2PHLS], container: [P2PHLSStats]}` as described [here](https://github.com/bemtv/bemtv/wiki/tutorial#3-build). If you have any other problems, please let me know. If not so, please consider closing this issue.

**Comment by flavioribeiro** [comment]
Regarding your scalability tests, how are you planning to do? Is there any event that you're planning to broadcast?

**Comment by macbroadcast** [comment]
Thanks, stupid mistake, i addet , but it seems i killed it.Is there an error log where i could have a look at ?
I put a copy of the index.html in here http://87.230.18.206:3000/ into http://87.230.18.206 but its allways showing white screen even when it display a video on port 3000. 
But my main concern right now is , that it does not work on Android and chromium !

**Comment by flavioribeiro** [comment]
Hi @macbroadcast,

First of all I would like you to define the main purpose of this issue, as every comment you add, you addresses a different question. 

All modern web browsers has console debugs, you can open it on chrome under menu -> tools -> developer tools, for example.

I saw on `http://87.230.18.206/` that all javascript files are missing:

``` console
Failed to load resource: the server responded with a status of 404 (Not Found) http://87.230.18.206/dist/jquery.js
Failed to load resource: the server responded with a status of 404 (Not Found) http://87.230.18.206/dist/underscore.js
Failed to load resource: the server responded with a status of 404 (Not Found) http://87.230.18.206/dist/clappr.light.min.js
Failed to load resource: the server responded with a status of 404 (Not Found) http://87.230.18.206/dist/p2phls.js
Failed to load resource: the server responded with a status of 404 (Not Found) http://87.230.18.206/dist/p2phlsstats.js
```

Regarding android support which should be opened as another issue, I have it running on a flash-enabled nexus as you can see [here](https://twitter.com/flavioribeiro/status/497522528496402432). 

BemTV needs flash support to intercept chunks requests, but I'm planning to make some tests with [dash.js](https://github.com/Dash-Industry-Forum/dash.js) which in turn runs only on browsers that supports media source extensions.

I'll close this issue for now, feel free to add how many you want with subjects you're in doubt.
